language: csharp
solution: "./DEXTER_POKEMON_DATA_PARSER/POKEMON_PARSER/POKEMON_PARSER.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./DEXTER_POKEMON_DATA_PARSER/POKEMON_PARSER/POKEMON_PARSER.sln
script:
  - xbuild ./DEXTER_POKEMON_DATA_PARSER/POKEMON_PARSER/POKEMON_PARSER.sln
