matrix:
  include:
    - language: csharp
      solution: POKEMON_PARSER.sln
      before_script:
        - cd DEXTER_POKEMON_DATA_PARSER/POKEMON_PARSER/
        mono:
          - latest
          - 3.12.0
          - 3.10.0

    - language: android
      jdk: oraclejdk8
      android:
        components:
          - tools
          - android-25
          - build-tools-25.0.3
      before_script:
        - cd DEXTER_ANDROID
      script:
        - ./gradlew build connectedCheck

    - language: objective-c
      os: osx
      osx_image: xcode8.3
      before_script:
        - cd DEXTER
      script:
        - xcodebuild -workspace DEXTER.xcodeproj -scheme DEXTER
          -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' build test

notifications:
  email:
    - joshmilesproduction@gmail.com
