matrix:
  include:
    - language: csharp
      solution: POKEMON_PARSER.sln
      before_script:
        - cd DEXTER_POKEMON_DATA_PARSER/POKEMON_PARSER/
        mono:
          - latest
          - 3.12.0
          - 3.10.0
